language: perl
perl:
  - "5.18"


before_install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:webupd8team/java -y
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886 
  - sudo apt-get update -qq
  - sudo apt-get install debconf-utils
  - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  - printf "y\n\n\t\n" | sudo apt-get install oracle-java8-installer
#the funky echo does not work but ill will still keep it in for future reference
install:
- echo "future work"

