language: perl
perl:
  - "5.18"

jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
    - LMODVERSION="6.4.5"
    - LMODPREFIX="/opt/apps"
    - LMODPATH="/opt/apps/lmod/lmod/libexec"
    - EASYBUILD_PREFIX=~/.local/easybuild
    - EASYBUILDMODS=~/.local/easybuild/modules/all
    - EASYBUILD_MODULES_TOOL='Lmod'
  matrix:
    - MOLGENISVERSION="v16.04.1"
    - MOLGENISVERSION="v16.08.1" 

before_install:
#note: migth need cleanup here and there
#instal lua / lmod
  - sudo apt-get install liblua5.1-0 liblua5.1-0-dev liblua5.1-filesystem-dev liblua5.1-filesystem liblua5.1-posix-dev liblua5.1-posix lua5.1
  - wget https://github.com/TACC/Lmod/archive/6.4.5.tar.gz
  - tar -zxf 6.4.5.tar.gz
  - cd Lmod-*/ && sudo mkdir -p /opt/apps && ./configure --prefix=/opt/apps && sudo make install && cd $OLDPWD
  - export PATH=$PATH:$LMODPATH && . /opt/apps/lmod/lmod/init/profile
  - module av && module list
#install easybuild
  - wget https://raw.githubusercontent.com/hpcugent/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py
  - python --version
  - echo "travis-env:" $EASYBUILD_PREFIX $EASYBUILDMODS $EASYBUILD_MODULES_TOOL $MOLGENISVERSION $LMODVERSION $LMODPREFIX $LMODPATH 
  - export EASYBUILD_PREFIX=$HOME/.local/easybuild && mkdir -p $HOME/.local/easybuild && python bootstrap_eb.py $HOME/.local/easybuild && module use $HOME/.local/easybuild/modules/all
  - export EASYBUILD_MODULES_TOOL='Lmod' && module load EasyBuild && eb -l eb/Molgenis-Compute-${MOLGENISVERSION}.eb

#easybuild
#molgenis-compute <- the depencany hell begins here
install:
  - echo "Future work. You can use it from the source dir"
