language: perl
perl:
  - "5.18"

before_install:
#install oracle java 8
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:webupd8team/java -y
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886 
  - sudo apt-get update -qq
  - sudo apt-get install debconf-utils
  - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  - printf "y\n\n\t\n" | sudo apt-get install oracle-java8-installer
#note: migth be optimised here and there
#instal lua / lmod
  - sudo apt-get install liblua5.1-0 liblua5.1-0-dev liblua5.1-filesystem-dev liblua5.1-filesystem liblua5.1-posix-dev liblua5.1-posix lua5.1
  - wget https://github.com/TACC/Lmod/archive/6.4.5.tar.gz
  - tar -zxf 6.4.5.tar.gz
  - cd Lmod-*/ && sudo mkdir -p /opt/apps && ./configure --prefix=/opt/apps && sudo make install && cd $OLDPWD
  - . /opt/apps/lmod/lmod/init/profile
  - module av && module list
#install easybuild
  - wget https://raw.githubusercontent.com/hpcugent/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py
  - python --version
  - export EASYBUILD_PREFIX=$HOME/.local/easybuild && mkdir -p $HOME/.local/easybuild && python bootstrap_eb.py $HOME/.local/easybuild && module use $HOME/.local/easybuild/modules/all
  - export EASYBUILD_MODULES_TOOL='Lmod' && module load EasyBuild && eb eb/Molgenis-Compute-v16.04.1.eb -f -L
#  - export PATH=$PATH:/opt/apps/lmod/lmod/libexec && . /opt/apps/lmod/lmod/init/profile && module use $HOME/.local/easybuild/modules/all && module load EasyBuild && eb eb/Molgenis-Compute-v16.04.1.eb -f -l   
#init lmod
#$ ln -s /opt/apps/lmod/lmod/init/profile /etc/profile.d/z00_lmod.sh
#$ ln -s /opt/apps/lmod/lmod/init/cshrc   /etc/profile.d/z00_lmod.csh
#
#easybuild
#molgenis-compute <the depencany hell begins here
install:
  - echo "future work. you can use it from the source dir"
  - make test
